# Generated by Django 6.1.2 on 2026-10-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import eingang.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField()),
                ("line_id", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
                ),
                ("unit_code", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "unit_price",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "net_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("tax_category", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "tax_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
            ],
            options={
                "db_table": "invoice_lines",
            },
        ),
        migrations.CreateModel(
            name="RuleExplanation",
            fields=[
                ("rule_id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("plain_text", models.CharField(max_length=300)),
                ("fix_hint", models.CharField(max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[("curated", "Curated"), ("llm", "Llm")], max_length=16
                    ),
                ),
                ("prompt_version", models.CharField(blank=True, max_length=32, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rule_explanations",
            },
        ),
        migrations.CreateModel(
            name="ValidationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("warnings", "Warnings"),
                            ("invalid", "Invalid"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        max_length=16,
                    ),
                ),
                ("engine", models.CharField(max_length=200)),
                ("xsd_ok", models.BooleanField(null=True)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("fatal_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("ran_at", models.DateTimeField()),
            ],
            options={
                "db_table": "validation_reports",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("upload", "Upload"), ("email", "Email"), ("sample", "Sample")],
                        max_length=16,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("storage_key", models.CharField(max_length=500)),
                ("text_storage_key", models.CharField(blank=True, max_length=500, null=True)),
                ("received_at", models.DateTimeField()),
                ("sender_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("xml", "Xml"),
                            ("hybrid_pdf", "Hybrid Pdf"),
                            ("legacy_zugferd1", "Legacy Zugferd1"),
                            ("hybrid_pdf_unsupported", "Hybrid Pdf Unsupported"),
                            ("pdf_text", "Pdf Text"),
                            ("pdf_no_text", "Pdf No Text"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("format_label", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("needs_review", "Needs Review"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("exported", "Exported"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=32,
                    ),
                ),
                (
                    "processing_step",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("detect", "Detect"),
                            ("validate", "Validate"),
                            ("extract", "Extract"),
                            ("check", "Check"),
                            ("done", "Done"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("workflow_id", models.CharField(blank=True, default="", max_length=200)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_id", models.CharField(max_length=3)),
                ("code", models.CharField(max_length=40)),
                (
                    "severity",
                    models.CharField(
                        choices=[("block", "Block"), ("warn", "Warn"), ("info", "Info")],
                        max_length=8,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="invoices.document",
                    ),
                ),
            ],
            options={
                "db_table": "checks",
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")], max_length=16
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField()),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="invoices.document",
                    ),
                ),
            ],
            options={
                "db_table": "approvals",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("document.received", "Document Received"),
                            ("document.duplicate_upload", "Document Duplicate Upload"),
                            ("processing.started", "Processing Started"),
                            ("processing.step", "Processing Step"),
                            ("processing.failed", "Processing Failed"),
                            ("processing.completed", "Processing Completed"),
                            ("invoice.fields_edited", "Invoice Fields Edited"),
                            ("check.created", "Check Created"),
                            ("check.resolved", "Check Resolved"),
                            ("review.completed", "Review Completed"),
                            ("approval.decided", "Approval Decided"),
                            ("review.sent_back", "Review Sent Back"),
                            ("document.reopened", "Document Reopened"),
                            ("reminder.sent", "Reminder Sent"),
                            ("export.created", "Export Created"),
                            ("document.deleted", "Document Deleted"),
                        ],
                        max_length=40,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="invoices.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "events",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("syntax", models.CharField(blank=True, max_length=8, null=True)),
                ("profile", models.CharField(blank=True, max_length=32, null=True)),
                ("spec_id", models.CharField(blank=True, max_length=255, null=True)),
                ("is_einvoice", models.BooleanField(default=False)),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[("xml", "Xml"), ("llm", "Llm"), ("manual", "Manual")],
                        max_length=16,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=200, null=True)),
                ("type_code", models.IntegerField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("buyer_reference", models.CharField(blank=True, max_length=200, null=True)),
                ("order_reference", models.CharField(blank=True, max_length=200, null=True)),
                ("seller_name", models.CharField(blank=True, max_length=500, null=True)),
                ("seller_vat_id", models.CharField(blank=True, max_length=32, null=True)),
                ("seller_tax_number", models.CharField(blank=True, max_length=64, null=True)),
                ("seller_street", models.CharField(blank=True, max_length=500, null=True)),
                ("seller_postcode", models.CharField(blank=True, max_length=32, null=True)),
                ("seller_city", models.CharField(blank=True, max_length=200, null=True)),
                ("seller_country_code", models.CharField(blank=True, max_length=2, null=True)),
                ("seller_email", models.CharField(blank=True, max_length=254, null=True)),
                ("buyer_name", models.CharField(blank=True, max_length=500, null=True)),
                ("buyer_vat_id", models.CharField(blank=True, max_length=32, null=True)),
                ("buyer_tax_number", models.CharField(blank=True, max_length=64, null=True)),
                ("buyer_street", models.CharField(blank=True, max_length=500, null=True)),
                ("buyer_postcode", models.CharField(blank=True, max_length=32, null=True)),
                ("buyer_city", models.CharField(blank=True, max_length=200, null=True)),
                ("buyer_country_code", models.CharField(blank=True, max_length=2, null=True)),
                ("buyer_email", models.CharField(blank=True, max_length=254, null=True)),
                ("payee_iban", models.CharField(blank=True, max_length=34, null=True)),
                ("payee_bic", models.CharField(blank=True, max_length=11, null=True)),
                ("payment_terms", models.TextField(blank=True, null=True)),
                (
                    "line_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "allowance_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "charge_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "net_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "tax_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "gross_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "prepaid_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "payable_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("notes", models.JSONField(blank=True, null=True)),
                ("tax_breakdown", models.JSONField(blank=True, default=list)),
                ("field_confidence", models.JSONField(blank=True, default=dict)),
                ("field_evidence", models.JSONField(blank=True, default=dict)),
                ("text_truncated", models.BooleanField(default=False)),
                ("normalised_number", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="invoices.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
            },
        ),
    ]
