# Generated by Django 6.1.2 on 2026-10-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="validationreport",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_report",
                to="invoices.document",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["organization", "status"], name="documents_org_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "sha256"),
                name="documents_org_sha256_live_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="check",
            index=models.Index(fields=["document", "resolved_at"], name="checks_doc_resolved_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["document", "created_at"], name="events_doc_created_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "supplier", "normalised_number"],
                name="invoices_org_supplier_num_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.UniqueConstraint(
                fields=("invoice", "position"), name="invoice_lines_invoice_pos_uniq"
            ),
        ),
    ]
