# Generated by Django 6.1.2 on 2026-10-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="prompt_version",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
