# Generated by Django 6.1.2 on 2026-10-09 17:05

import django.db.models.deletion
from django.db import migrations, models

import eingang.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmCache",
            fields=[
                (
                    "request_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("response_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "llm_cache",
            },
        ),
        migrations.CreateModel(
            name="LlmCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purpose", models.CharField(max_length=64)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("prompt_version", models.CharField(max_length=32)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("cached_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cost", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("cache_hit", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("error", "Error"),
                            ("refused_budget", "Refused Budget"),
                            ("refused_disabled", "Refused Disabled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "llm_calls",
            },
        ),
    ]
