# Generated by Django 6.1.2 on 2026-10-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmcall",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DB_SET_NULL,
                related_name="llm_calls",
                to="accounts.organization",
            ),
        ),
    ]
