# Generated by Django 6.1.2 on 2026-10-09 18:39

from django.db import migrations, models

import eingang.clock


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0002_alter_llmcall_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcall",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="llmcall",
            name="created_at",
            field=models.DateTimeField(default=eingang.clock.now),
        ),
    ]
