// The design's icon names (design/export/eingang-ui.js) mapped to lucide-vue-next icons.
import {
  Archive,
  Ban,
  Building2,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  Clock,
  Copy,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileCode,
  FileText,
  Gauge,
  Hourglass,
  Inbox,
  Info,
  Landmark,
  LoaderCircle,
  Lock,
  type LucideIcon,
  MessageSquare,
  Minus,
  OctagonAlert,
  Paperclip,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  SlidersHorizontal,
  TriangleAlert,
  Upload,
  User,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-vue-next";

export const ICONS = {
  inbox: Inbox,
  check: Check,
  "circle-check": CircleCheck,
  "check-check": CheckCheck,
  hourglass: Hourglass,
  loader: LoaderCircle,
  triangle: TriangleAlert,
  octagon: OctagonAlert,
  info: Info,
  x: X,
  search: Search,
  upload: Upload,
  download: Download,
  "file-text": FileText,
  "file-code": FileCode,
  pencil: Pencil,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  user: User,
  building: Building2,
  archive: Archive,
  gauge: Gauge,
  sliders: SlidersHorizontal,
  more: Ellipsis,
  plus: Plus,
  landmark: Landmark,
  copy: Copy,
  eye: Eye,
  "eye-off": EyeOff,
  clock: Clock,
  ban: Ban,
  message: MessageSquare,
  lock: Lock,
  refresh: RefreshCw,
  external: ExternalLink,
  circle: Circle,
  minus: Minus,
  "circle-alert": CircleAlert,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  paperclip: Paperclip,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
