# Generated by Django 6.1.2 on 2026-10-09 16:56

import django.db.models.deletion
from django.db import migrations, models

import eingang.db


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("standard", "Standard"), ("sandbox", "Sandbox")],
                        default="standard",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("vat_id", models.CharField(blank=True, max_length=32, null=True)),
                ("four_eyes", models.BooleanField(default=True)),
                ("duplicate_window_days", models.PositiveIntegerField(default=30)),
                ("reminder_after_days", models.PositiveIntegerField(default=3)),
                ("llm_calls_used", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "organizations",
                "indexes": [models.Index(fields=["expires_at"], name="organizations_expires_idx")],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("accountant", "Accountant"),
                            ("approver", "Approver"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
