# Generated by Django 6.1.2 on 2026-10-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import eingang.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv_invoices", "Csv Invoices"),
                            ("csv_lines", "Csv Lines"),
                            ("zip_bundle", "Zip Bundle"),
                        ],
                        max_length=16,
                    ),
                ),
                ("document_ids", models.JSONField(default=list)),
                ("storage_key", models.CharField(max_length=500)),
                ("row_count", models.PositiveIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_batches",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "export_batches",
            },
        ),
    ]
