# Generated by Django 6.1.2 on 2026-10-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import eingang.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("invoices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500)),
                ("normalised_name", models.CharField(max_length=500)),
                ("vat_id", models.CharField(blank=True, max_length=32, null=True)),
                ("invoice_count", models.PositiveIntegerField(default=0)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "suppliers",
            },
        ),
        migrations.CreateModel(
            name="SupplierIban",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=eingang.db.new_id, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("iban", models.CharField(max_length=34)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("confirmation_note", models.TextField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_seen_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ibans",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "supplier_ibans",
            },
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["organization", "normalised_name"], name="suppliers_org_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vat_id__isnull", False)),
                fields=("organization", "vat_id"),
                name="suppliers_org_vat_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplieriban",
            constraint=models.UniqueConstraint(
                fields=("supplier", "iban"), name="supplier_ibans_iban_uniq"
            ),
        ),
    ]
